---
schema: dev/Configurables/v1
metadata:
  schema: metadata/Document/v1
  name: dev-configurables
  layeringDefinition:
    abstract: false
    layer: site
  storagePolicy: cleartext
data:
  hostcidr: 192.168.22.0/24
...
